[package]
name = "bmfont"
version = "0.2.1"
authors = ["kalita.alexey <kalita.alexey@outlook.com>"]
description = "bitmap font config parser"
license = "MIT OR Apache-2.0"
repository = "https://github.com/KalitaAlexey/bmfont-rust"
keywords = ["bitmap", "font"]

exclude = [
    "examples/*",
    "tests/*",
    "*.fnt",
    "*.png",
]

[dev-dependencies]
glium = "^0.16.0"
image = "^0.10.3"

