[package]
name = "bmfont"
version = "0.1.0"
authors = ["kalita.alexey <kalita.alexey@outlook.com>"]
description = "bitmap font config parser"
license = "MIT"
repository = "https://github.com/KalitaAlexey/bmfont-rust"
keywords = ["bitmap", "font"]

[dev-dependencies]
glium = "0.13"
image = "0.6"